films:
    path: /index
    controller: App\Controller\FilmController::show

ajoutFilm:
    path: /ajout/film
    controller: App\Controller\FilmController::ajoutFilm

details:
    path: detail/film/{id}
    controller: App\Controller\FilmController::details

delete:
    path: delete/film/{id}
    controller: App\Controller\FilmController::delete